name: Test

on:
  push:
    branches:
      - main
  pull_request:

env:
  FOUNDRY_PROFILE: lite
  MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
  ARBITRUM_RPC_URL: ${{ secrets.ARBITRUM_RPC_URL }}
  OPTIMISM_RPC_URL: ${{ secrets.OPTIMISM_RPC_URL }}

jobs:
  check:
    name: Forge Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Install dependencies 📦
        run: yarn install --frozen-lockfile

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run Forge build
        run: forge build

      - name: Run tests on mainnet
        run: forge test -vvv
        env:
          CHAIN_ID: 1

      - name: Run tests on Arbitrum
        run: forge test -vvv
        env:
          CHAIN_ID: 42161

      - name: Run tests on Optimism
        run: forge test -vvv
        env:
          CHAIN_ID: 10

      - name: Run snapshot
        run: NO_COLOR=1 forge snapshot >> $GITHUB_STEP_SUMMARY
        env:
          CHAIN_ID: 1
